In [ ]:
import numpy as np

In [ ]:
#ARRAY OF ONES
ones = np.ones((4,3,4),dtype=int)
print(ones)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [ ]:
#ARRAY OF ZEROS
zeros = np.zeros((5,3,4),dtype=np.int)
print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


<ipython-input-5-4f2e5075a46e>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  zeros = np.zeros((5,3,4),dtype=np.int)


In [ ]:
#ARRAY WITH RANDOM VALUES
s = np.random.random((2,2))
print(s)

[[0.71424711 0.64179662]
 [0.15657028 0.22929978]]


In [ ]:
#EMPTY ARRAY
empty_array = np.empty((3,2))
print(empty_array)

[[4.87923980e-310 0.00000000e+000]
 [8.82893671e+199 7.08519663e+194]
 [9.79652183e+252 1.17075159e+214]]


In [ ]:
#FULL ARRAY
full_array = np.full((3,2),7)
print(full_array)

[[7 7]
 [7 7]
 [7 7]]


In [ ]:
#ARRAY OF EVENLY SPACED VALUES
evenspaced_array = np.arange(10,25,5)
print(evenspaced_array)

[10 15 20]
